Ut3 tapas
AlvaroLC/Programacion-Multimedia-Dispositivos-Moviles pull request #1
Opened 2021-10-22 17:20 UTC by AlvaroLC

## Description
Implementación de las vistas de la actividad propuesta en clase

## Related Issue

## How has this been tested?

## Design UI
![image](https://user-images.githubusercontent.com/51322166/138499793-b6a507ef-e458-4e40-8e12-49b3313954a0.png)
![image](https://user-images.githubusercontent.com/51322166/138499814-5acca67c-4d04-488c-8dcf-8a9b32a1a2d7.png)

## Screenshots or Video
![image](https://user-images.githubusercontent.com/51322166/138499866-e8173e23-5a73-4af7-a4e9-026bd02a9c54.png)
![image](https://user-images.githubusercontent.com/51322166/138499908-243e3044-db65-4588-82f3-a1afcf8f5704.png)

2021-10-27 09:25 UTC, ghost requested changes
Hola Álvaro,
Por favor, revisa los comentarios y corrige lo que te indico.
Además, revisa si la rama debe hacer un "merge" con develop o con u3_ui_layout.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +        android:id="@+id/bloque01"
El naming bloque01 no ofrece contexto, no facilita identificar que es esta vista.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:id="@+id/image01"
El naming image01 no ofrece contexto, no facilita identificar que es esta imagen.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:id="@+id/text01"
El naming text01 no ofrece contexto, no facilita identificar que es este texto.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:id="@+id/text02"
El naming text02 no ofrece contexto, no facilita identificar que es esta vista.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:id="@+id/bloque02"
El naming bloque02 no ofrece contexto, no facilita identificar que es esta vista.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +                android:id="@+id/text03"
El naming text03 no ofrece contexto, no facilita identificar que es este texto.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +                android:id="@+id/imageStars"
El naming imageStart ofrece contexto sobre la imagen, "estrellas". Quizás si indicas la finalidad de esta imagen de más contexto, por ejemplo, iv_rating, image_rating, rating_view...

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +                android:id="@+id/text04"
El naming text04 no ofrece contexto, no facilita identificar que es este texto.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +                android:id="@+id/text05"
El naming text05 no ofrece contexto, no facilita identificar que es este texto.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:id="@+id/image02"
El naming image02 no ofrece contexto, no facilita identificar que es esta imagen.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:id="@+id/image03"
El naming image03 no ofrece contexto, no facilita identificar que es esta imagen.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:id="@+id/image04"
El naming image04 no ofrece contexto, no facilita identificar que es esta imagen.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:id="@+id/image05"
El naming image05 no ofrece contexto, no facilita identificar que es esta imagen.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +                android:id="@+id/text06"
El naming text06 no ofrece contexto, no facilita identificar que es este texto.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +                android:id="@+id/image06"
El naming image06 no ofrece contexto, no facilita identificar que es esta imagen.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +        android:id="@+id/navBar"
El naming navBar no ofrece contexto, no facilita identificar que es esta vista.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +        android:layout_height="40dp"
usa el recurso dimen en vez de meter un valor fijo.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:id="@+id/image01"
El naming no ofrece contexto, no facilita identificar que es esta vista.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:padding="5dp"
Si todas las imágenes van a tener un mismo padding, ¿por qué no creas un estilo?

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:id="@+id/text01"
El naming no ofrece contexto, no facilita identificar que es esta vista.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +        android:id="@+id/bloqueEncabezado"
Intenta usar el inglés, si no se te ocurre nada, pregúntamelo. Aquí podría valerte: header_view o header_wrapper

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +        android:layout_height="140dp"
Usa dimen en vez de meter el valor a mano.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +        android:padding="15dp">
Usa dimen en vez de meter el valor a mano. ¿crear un estilo?

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:id="@+id/text02"
El naming no ofrece contexto, no facilita identificar que es esta vista.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:textSize="25sp"
Usa dimen o créate un estilo

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:id="@+id/text03"
El naming no ofrece contexto, no facilita identificar que es esta vista.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:textSize="14sp"
Usa dimen o créate un estilo.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:id="@+id/image02"
El naming no ofrece contexto, no facilita identificar que es esta vista.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            style="@style/Icon"
El naming no ofrece contexto, no facilita identificar que es este estilo. Puedes usar algo como IngredientsIconStyle por ejmplo,

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +        android:id="@+id/bloqueOpciones"
Naming: options_view o options_wrapper

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +        android:padding="15dp">
Usa dimen o piensa si puedes crearte un estilo si este valor se repite.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:paddingStart="20dp"
usa dimen o piensa si puedes crear un estilo si este valor se repite.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:id="@+id/text04"
El naming no ofrece contexto, no facilita identificar que es esta vista.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:textSize="14sp"
Usa dimens o piensa si puedes crearte un estilo si el valor se repite en los mismos elementos.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:paddingStart="30dp"
Usa dimens o piensa si puedes crearte un estilo si el valor se repite en los mismos elementos.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:id="@+id/text05"
El naming no ofrece contexto, no facilita identificar que es esta vista.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:textSize="14sp"
Usa dimens o créate  un estilo si crees que el valor se repite.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:paddingStart="30dp"
Usa dimens o créate un estilo si crees que el valor se repite.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:id="@+id/text06"
El naming no ofrece contexto, no facilita identificar que es esta vista.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:textSize="14sp"
Usa dimens o créate un estilo si crees que el valor se repite.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:paddingEnd="20dp"
Usa dimens o créate un estilo si crees que el valor se repite.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:id="@+id/text07"
El naming no ofrece contexto, no facilita identificar que es esta vista.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:textSize="14sp"
Usa dimens o créate un estilo si crees que el valor se repite.

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/values/dimens.xml
> +        <item name="space_vertical">10dp</item>
Tabula los ficheros: ctrl +L

2021-10-27 09:25 UTC, ghost commented on app/src/main/res/values/styles.xml
> +    <style name="Icon">
El naming no ofrece contexto, no facilita identificar que es esta vista.

2021-10-28 10:06 UTC, AlvaroLC commented
@jmperezra ¡Hola Chema! Ya hice una corrección de la PR con los cambios que me comentaste. He puesto nombres más descriptivos a los elementos. Y he hecho más uso de estilos y dimens. Aún no he implementado lo de los nombres por programación que nos dijiste ayer. Será lo siguiente que haga. Hice dos push con correcciones, la última es la que se llama "Corrección Buena PR (28/10/2021)" cuyo enlace es https://github.com/AlvaroLC/Programacion-Multimedia-Dispositivos-Moviles/pull/1/commits/93d0bf4daef34b15da6a7d5d7f38b6f139ea4d8b Pero la gran mayoria de cambios entre ambas PR los podrás ver en la anterior. https://github.com/AlvaroLC/Programacion-Multimedia-Dispositivos-Moviles/pull/1/commits/cea89c9d0b093594a446df9e27865efe6082596a  Ya que en la última solo tabulé los ficheros y cambié un par de cosas. 
Un saludo.

2021-10-28 15:19 UTC, ghost requested changes
Álvaro, te he dejado varios comentarios que te resumo aquí:

- El nombre de los id de las vistas debe estar separado por underscore _ y en minúsculas. Además, deben ser descriptivos.
- El nombre de los dimens debe estar separado por underscore _ y en minúsculas.
- El nombre de los estilos debe ser CamelCase

Es muy importante que, además de diseñar la vista, se preste atención a estas convenciones del código para seguir el mismo criterio en todo el proyecto y que no sea un "Frankenstein"

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +        android:padding="@dimen/padingRestaurant1">
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_vertical o space_horizontal, cualquiera de los dos te valdría.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:paddingStart="@dimen/PaddingStart"
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_vertical o space_horizontal, cualquiera de los dos te valdría.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:paddingStart="@dimen/PaddingStart"
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_vertical o space_horizontal, cualquiera de los dos te valdría.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +                android:paddingStart="@dimen/PaddingStart"
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_vertical o space_horizontal, cualquiera de los dos te valdría.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +                android:padding="@dimen/PaddingIcons"
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_icons

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +                android:src="@drawable/estrellas" />
cambia estrellas por stars

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +                android:paddingStart="@dimen/PaddingStart"
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_vertical o space_horizontal, cualquiera de los dos te valdría.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +                android:paddingStart="@dimen/PaddingStart"
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_vertical o space_horizontal, cualquiera de los dos te valdría.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:padding="@dimen/PaddingIcons"
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_icons

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:id="@+id/imageIconDeliveroo"
El id debería tener un nombre con underscore, por ejemplo, image_icon_deliveroo

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:padding="@dimen/PaddingIcons"
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_icons

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:id="@+id/imageIconGlovo"
El id debería llevar underscore, por ejemplo, image_icon_glovo

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:padding="@dimen/PaddingIcons"
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_icons

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:id="@+id/imageIconJustEat"
El id debería llevar underscore _ guiones bajos

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant1.xml
> +            android:padding="@dimen/PaddingIcons"
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_icons

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +        android:id="@+id/navBarApplication"
El id debería llevar underscore _ guión bajo

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +        android:layout_height="@dimen/NavBarHeight"
Los dimens deberían estar separados por underscore _

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:padding="@dimen/PaddingIcons"
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_icons

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +        android:padding="@dimen/HeaderPadding">
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_vertical o space_horizontal, cualquiera de los dos te valdría.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            style="@style/typeRestaurantView"
El nombre del estilo debería usar CamelCase, por ejemplo, TypeRestaurantStyle

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +        <androidx.appcompat.widget.AppCompatImageView
Cambia este AppCompatImageView por un RatingView

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:src="@drawable/estrella2" />
Cambia estrella por star2

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:src="@drawable/corazon1" />
Cambia corazón por heart o Like o i_like_it

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +        android:padding="@dimen/optionsPadding">
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_vertical o space_horizontal, cualquiera de los dos te valdría.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            style="@style/optionStyle"
El naming de los estilos es CamelCase, por ejemplo, OptionStyle.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:paddingStart="@dimen/optionPaddingStart"
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_vertical o space_horizontal, cualquiera de los dos te valdría.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            style="@style/optionStyle"
El nombre del estilo es CamelCase.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:paddingStart="@dimen/optionPaddingStart"
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_vertical o space_horizontal, cualquiera de los dos te valdría.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            style="@style/optionStyle"
El nombre de los estilos es con CamelCase

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant2.xml
> +            android:paddingEnd="@dimen/optionPaddingEnd"
En dimen, string.... excepto es estilos, deberías usar underscore, por ejemplo, llámalo space_vertical o space_horizontal, cualquiera de los dos te valdría.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:id="@+id/image01"
Usa nombres descriptivos.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:id="@+id/text01"
Usa nombres descriptivos.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:id="@+id/text02"
Usa nombres descriptivos.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:paddingStart="5dp"
Usa @dimens

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:id="@+id/text03"
Usa nombres descriptivos.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:paddingStart="5dp"
Usa @dimens

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:layout_width="70dp"
Usa dimens

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:src="@drawable/estrellas" />
Usa mejor nombres en inglés: starts

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:id="@+id/text04"
Usa nombres descriptivos.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:paddingStart="5dp"
Usa @dimens

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:id="@+id/text05"
Usa @dimens

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:paddingStart="5dp"
Usa @dimens

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:id="@+id/image02"
Usa nombres descriptivos.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:padding="5dp"
Usa dimens

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:src="@drawable/ubereats" />
El formato para las imagenes debería ser algo como ic_uber_eats

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:id="@+id/image03"
Usa nombres descriptivos.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:padding="5dp"
Usa @dimens

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:id="@+id/image04"
Usa nombres descriptivos

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:padding="5dp"
Usa @dimens

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:src="@drawable/glovo" />
En imágenes intenta seguir el naming: ic_glovo

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:id="@+id/image05"
Usa un nombre descriptivo

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:padding="5dp"
Usa dimen

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:id="@+id/text06"
Usa un nombre identificativo

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:id="@+id/image06"
Usa un nombre identificativo

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/layout/view_exercise_restaurant_constraint.xml
> +        android:src="@drawable/etiqueta" />
Usa un nombre en inglés, por ejemplo, ic_label

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/values/dimens.xml
> +    <dimen name="SpaceVertical">
Los nombres de los dimens deben estar separados por underscore

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/values/dimens.xml
> +        <item name="space_vertical">10dp</item>
tabula los ficheros antes de subirlos.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/values/dimens.xml
> +    <dimen name="optionsPadding">
Usa underscore y mínúsculas en los nombres de los estilos. Cámbialo en todo el fichero.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/values/dimens.xml
> +        <item name="padding">15dp</item>
USa dimens

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/values/dimens.xml
> +    <dimen name="optionPaddingStart">
Usa underscore y mínúsculas en los nombres de los estilos. Cámbialo en todo el fichero.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/values/dimens.xml
> +        <item name="paddingStart">28dp</item>
Usa dimensiones

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/values/dimens.xml
> +    <dimen name="optionPaddingEnd">
Usa underscore y mínúsculas en los nombres de los estilos. Cámbialo en todo el fichero.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/values/dimens.xml
> +    <dimen name="padingRestaurant1">
Usa underscore y mínúsculas en los nombres de los estilos. Cámbialo en todo el fichero.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/values/styles.xml
> +    <style name="typeRestaurantView">
Usa CamelCase en los estilos, como tienes en otros estilos en el mismo fichero.

2021-10-28 15:19 UTC, ghost commented on app/src/main/res/values/styles.xml
> +    <style name="optionStyle">
Usa CamelCase en los estilos, como tienes en otros estilos en el mismo fichero.

2021-11-11 16:08 UTC, jmperezra approved these changes
Genial @AlvaroLC , los cambios están muy bien. Puedes hacer el merge de la rama.
Sólo como sugerencia, intenta no añadir un prefijo a los namings que sea el tipo de dato que es, es decir, si uso un TextView poner como id = text_title, no aporta mucho el text, pues ya se que es un TextView. Esto es una forma de "acoplarse" al componente. Usa algo más genérico como:
Para textos: label.
Para Editext: inputs.
Para botones: actions
Para imágenes: si es una imagen de un usuario, avatar_user o profile_user, etc..

2021-11-11 17:10 UTC, merged